### ISSUE TITLE
using glua functions in new thread

### ISSUE THREAD

**Issue by rautyrauty** [Thomasims/GThread#3]
Is it possible using this module to use glua functions in a new thread? Here is my code:
```lua
require "threading"

local thread = threading.newThread()
thread:Run( 
    function()
        print("httpzapros.lua : Run thread")
        http.Fetch(
            "http://date.jsontest.com/",
            function(body)
                print(util.JSONToTable(body).time)
            end,
            function(body)
                print("failure")
            end
        )
    end 
)
```
error: lua/httpzapros.lua:7: attempt to index global 'http' (a nil value)

**Comment by Thomasims** [comment]
Unfortunately no; I would have to essentially reimplement the lua interface for those libraries and even then I can't make any assumptions about the thread safety of internal functions.

The most versatile approach would probably be to allow binary modules to be loaded from threaded contexts but the modules themselves would need to be either very simple or written with the understanding that they're being run from a side thread.

Either way I have no plan to keep updating this module it was just an experiment in off-loading compute-heavy tasks in lua.

**Comment by rautyrauty** [comment]
Ok, thanks.
